@startuml LightSm

' STATES
state OFF
state ON1

' STATE HANDLERS
[*] -> OFF

OFF: enter / this.count++;
OFF: enter / this.turnOff();
OFF --> ON1: ON_PRESS

note "Increment count just to show we can" as N1

ON1: enter / this.turnOn();
ON1: enter / this.resetTimer();
ON1 --> OFF: OFF_PRESS
ON1 --> OFF: [this.isTimerExpired()]

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "JavaScript"
RenderConfig.JavaScript.ExtendsSuperClass = "LightSmBase"
'/
@enduml